"""(STABLE) Added some fields in notion page model

Revision ID: 2fbefe53725c
Revises: 676631413b21
Create Date: 2025-06-16 18:24:27.756401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbefe53725c'
down_revision: Union[str, None] = '676631413b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_pages', sa.Column('notes_block_id', sa.String(), nullable=True))
    op.add_column('notion_pages', sa.Column('references_block_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notion_pages', 'references_block_id')
    op.drop_column('notion_pages', 'notes_block_id')
    # ### end Alembic commands ###
