"""(STABLE) removed fields from notion page model

Revision ID: 37407c620843
Revises: 2fbefe53725c
Create Date: 2025-06-17 10:34:35.114526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37407c620843'
down_revision: Union[str, None] = '2fbefe53725c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notion_pages', 'references_block_id')
    op.drop_column('notion_pages', 'notes_block_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_pages', sa.Column('notes_block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notion_pages', sa.Column('references_block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
