"""upgraded userimages model

Revision ID: 58f988d7b836
Revises: 7718c3575cca
Create Date: 2025-06-18 18:45:40.955014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f988d7b836'
down_revision: Union[str, None] = '7718c3575cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('appwrite_link', sa.String(), nullable=False))
    op.drop_constraint(op.f('user_images_file_id_key'), 'user_images', type_='unique')
    op.drop_column('user_images', 'filename')
    op.drop_column('user_images', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_images', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_images_file_id_key'), 'user_images', ['file_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_images', 'appwrite_link')
    # ### end Alembic commands ###
