"""(STABLE) Added notionDB id for user

Revision ID: 676631413b21
Revises: b329fc3c527a
Create Date: 2025-06-16 12:28:02.689336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676631413b21'
down_revision: Union[str, None] = 'b329fc3c527a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notionid', sa.Column('database_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notionid', 'database_id')
    # ### end Alembic commands ###
