"""Added category field in userimages

Revision ID: bb42109a2a01
Revises: 58f988d7b836
Create Date: 2025-06-20 18:53:03.513655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb42109a2a01'
down_revision: Union[str, None] = '58f988d7b836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_categories', ['category_name'])
    op.add_column('user_images', sa.Column('category', sa.String(), nullable=False))
    op.create_foreign_key(None, 'user_images', 'user_categories', ['category'], ['category_name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_images', type_='foreignkey')
    op.drop_column('user_images', 'category')
    op.drop_constraint(None, 'user_categories', type_='unique')
    # ### end Alembic commands ###
