"""Fixed double initial page creation issue (STABLE)

Revision ID: e4560c87edfb
Revises: 9ab7fe46a7fa
Create Date: 2025-06-14 12:14:52.601709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4560c87edfb'
down_revision: Union[str, None] = '9ab7fe46a7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notion_pages', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notion_pages', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_pages', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('notion_pages', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
